#!/bin/bash
# safe_clean.sh — Safely empty node_modules and Python venvs
# Usage: ./safe_clean.sh [--dry-run] [--generate] [SEARCH_PATH]
#   --dry-run   Preview only, no changes
#   --generate  Generate missing package.json/requirements for SKIP'd dirs
# Default SEARCH_PATH: $HOME

set -euo pipefail
IFS=$'\n'

# ─── Args ────────────────────────────────────────────────────────────────────
DRY_RUN=false
GENERATE=false
SEARCH_PATH="$HOME"

for arg in "$@"; do
  case "$arg" in
    --dry-run)  DRY_RUN=true ;;
    --generate) GENERATE=true ;;
    *)          SEARCH_PATH="$arg" ;;
  esac
done

echo "==> Search path : $SEARCH_PATH"
echo "==> Dry run     : $DRY_RUN"
echo "==> Generate    : $GENERATE"
echo ""

# ─── Counters & tracking ─────────────────────────────────────────────────────
bytes_freed=0
dry_run_total=0
node_count=0
venv_count=0
generated_count=0
declare -A node_proj_sizes
declare -A venv_sizes

# ─── Helpers ─────────────────────────────────────────────────────────────────
du_bytes() { du -sb "$1" 2>/dev/null | awk '{print $1}' || echo 0; }
human()    { numfmt --to=iec-i --suffix=B "$1" 2>/dev/null || echo "${1}B"; }
has_cmd()  { command -v "$1" &>/dev/null; }

has_node_lockfile() {
  local dir="$1"
  [[ -f "$dir/package.json" ]]      || \
  [[ -f "$dir/pnpm-lock.yaml" ]]    || \
  [[ -f "$dir/package-lock.json" ]] || \
  [[ -f "$dir/yarn.lock" ]]
}

has_python_lockfile() {
  local dir="$1"
  [[ -f "$dir/pyproject.toml" ]]  || \
  [[ -f "$dir/poetry.lock" ]]     || \
  [[ -f "$dir/uv.lock" ]]         || \
  ls "$dir"/requirements*.txt >/dev/null 2>&1
}

# ─── Detect Node project type ─────────────────────────────────────────────────
detect_node_type() {
  local dir="$1"
  [[ -f "$dir/next.config.js"   || -f "$dir/next.config.ts"   || -f "$dir/next.config.mjs" ]]   && echo "nextjs"           && return
  [[ -f "$dir/vite.config.js"   || -f "$dir/vite.config.ts"   ]]                                 && echo "vite"             && return
  [[ -f "$dir/svelte.config.js" || -f "$dir/svelte.config.ts" ]]                                 && echo "sveltekit"        && return
  [[ -f "$dir/nuxt.config.js"   || -f "$dir/nuxt.config.ts"   ]]                                 && echo "nuxt"             && return
  [[ -f "$dir/remix.config.js"  || -f "$dir/remix.config.ts"  ]]                                 && echo "remix"            && return
  [[ -f "$dir/astro.config.js"  || -f "$dir/astro.config.ts"  || -f "$dir/astro.config.mjs" ]]  && echo "astro"            && return
  [[ -f "$dir/wrangler.toml"    || -f "$dir/wrangler.json"    ]]                                 && echo "cloudflare-worker" && return
  [[ -f "$dir/pnpm-workspace.yaml" ]]                                                             && echo "pnpm-monorepo"    && return
  echo "generic"
}

# ─── Detect Python project type ──────────────────────────────────────────────
detect_python_type() {
  local dir="$1"
  [[ -f "$dir/.python-version" ]]             && echo "uv"         && return
  [[ -f "$dir/setup.py" || -f "$dir/setup.cfg" ]] && echo "setuptools" && return
  echo "pip"
}

# ─── Generate package.json ────────────────────────────────────────────────────
generate_package_json() {
  local proj_dir="$1"
  local nm="$proj_dir/node_modules"
  local out="$proj_dir/package.json"
  local proj_type proj_name deps="{}"
  proj_type=$(detect_node_type "$proj_dir")
  proj_name=$(basename "$proj_dir" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')

  # Best source: .package-lock.json (written by npm automatically)
  if [[ -f "$nm/.package-lock.json" ]] && has_cmd jq; then
    jq --arg name "$proj_name" --arg type "$proj_type" '{
      name: $name,
      version: "1.0.0",
      description: ("generated by safe_clean.sh — type: " + $type),
      dependencies: (
        .packages | to_entries
        | map(select(
            .key != "" and
            (.key | startswith("node_modules/")) and
            (.key | ltrimstr("node_modules/") | split("/") | length) == 1
          ))
        | map({ key: (.key | ltrimstr("node_modules/")), value: .value.version })
        | from_entries
      )
    }' "$nm/.package-lock.json" > "$out"
    echo "    GENERATED $out (from .package-lock.json, type: $proj_type)"
    return 0
  fi

  # Fallback: list top-level packages + read their versions
  if has_cmd node; then
    deps=$(node -e "
      const fs = require('fs'), path = require('path');
      const nm = '${nm}', pkgs = {};
      try {
        fs.readdirSync(nm).filter(d => !d.startsWith('.')).forEach(d => {
          const pj = path.join(nm, d, 'package.json');
          try { pkgs[d] = JSON.parse(fs.readFileSync(pj,'utf8')).version || '*'; } catch {}
        });
      } catch {}
      console.log(JSON.stringify(pkgs));
    " 2>/dev/null || echo "{}")
  fi

  cat > "$out" <<EOF
{
  "name": "$proj_name",
  "version": "1.0.0",
  "description": "generated by safe_clean.sh — type: $proj_type",
  "dependencies": $deps
}
EOF
  echo "    GENERATED $out (dir listing fallback, type: $proj_type)"
}

# ─── Generate Python manifest ─────────────────────────────────────────────────
generate_python_manifest() {
  local proj_dir="$1"
  local venv_dir="$2"
  local py_type out
  py_type=$(detect_python_type "$proj_dir")
  local pip="$venv_dir/bin/pip"

  if [[ ! -x "$pip" ]]; then
    echo "    SKIP-GEN  $venv_dir (no pip in venv)"
    return 1
  fi

  case "$py_type" in
    uv)
      # Generate pyproject.toml skeleton + requirements.txt for uv
      out="$proj_dir/requirements.txt"
      "$pip" freeze > "$out" 2>/dev/null
      echo "    GENERATED $out (pip freeze, uv project)"
      ;;
    setuptools|pip)
      out="$proj_dir/requirements.txt"
      "$pip" freeze > "$out" 2>/dev/null
      echo "    GENERATED $out (pip freeze)"
      ;;
  esac
}

# ─── Node: node_modules ──────────────────────────────────────────────────────
echo "── Node.js node_modules ─────────────────────────────────────────────────"

while IFS= read -r dir; do
  [[ "$dir" == *"/node_modules/"*"/node_modules" ]] && continue
  [[ -z "$(ls -A "$dir" 2>/dev/null)" ]] && continue
  proj_dir=$(dirname "$dir")

  if has_node_lockfile "$proj_dir"; then
    size=$(du_bytes "$dir")
    top_proj=$(echo "$proj_dir" | sed "s|$HOME/||" | cut -d'/' -f1-2)
    node_proj_sizes["$top_proj"]=$(( ${node_proj_sizes["$top_proj"]:-0} + size ))
    node_count=$((node_count + 1))
    if $DRY_RUN; then
      dry_run_total=$((dry_run_total + size))
      echo "    [dry-run] would empty $dir ($(human "$size"))"
    else
      rm -rf "${dir:?}"/*
      bytes_freed=$((bytes_freed + size))
      echo "    Emptied  $dir ($(human "$size") freed)"
    fi
  elif $GENERATE; then
    if $DRY_RUN; then
      echo "    [dry-run] would generate package.json in $proj_dir (type: $(detect_node_type "$proj_dir"))"
    else
      generate_package_json "$proj_dir" && generated_count=$((generated_count + 1))
    fi
  else
    echo "    SKIP  $dir (no lockfile — use --generate to create one)"
  fi
done < <(find "$SEARCH_PATH" \
  -type d -name "node_modules" \
  ! -path "*/node_modules/*/node_modules" \
  ! -path "$HOME/.cursor/*" \
  ! -path "$HOME/.windsurf/*" \
  ! -path "$HOME/.vscode/*" \
  ! -path "$HOME/.npm/_npx/*" \
  ! -path "$HOME/.bun/*" \
  ! -path "$HOME/.local/share/pnpm/*" \
  ! -path "$HOME/.cache/*" \
  ! -path "$HOME/.gradle/*" \
  ! -path "$HOME/.nvm/*" \
  2>/dev/null)

# ─── Python: .venv / venv / env ──────────────────────────────────────────────
echo ""
echo "── Python venvs ─────────────────────────────────────────────────────────"

while IFS= read -r dir; do
  [[ ! -f "$dir/pyvenv.cfg" ]] && { echo "    SKIP  $dir (no pyvenv.cfg)"; continue; }
  proj_dir=$(dirname "$dir")

  if has_python_lockfile "$proj_dir"; then
    size=$(du_bytes "$dir")
    venv_sizes["$dir"]=$size
    venv_count=$((venv_count + 1))
    if $DRY_RUN; then
      dry_run_total=$((dry_run_total + size))
      echo "    [dry-run] would empty lib/include in $dir ($(human "$size"))"
    else
      size_before=$(du_bytes "$dir")
      rm -rf "${dir:?}"/lib/python*/site-packages/* 2>/dev/null || true
      rm -rf "${dir:?}"/include/* 2>/dev/null || true
      bytes_freed=$((bytes_freed + size_before))
      echo "    Emptied  $dir ($(human "$size_before") freed)"
    fi
  elif $GENERATE; then
    if $DRY_RUN; then
      echo "    [dry-run] would generate requirements.txt in $proj_dir (type: $(detect_python_type "$proj_dir"))"
    else
      generate_python_manifest "$proj_dir" "$dir" && generated_count=$((generated_count + 1))
    fi
  else
    echo "    SKIP  $dir (no lockfile — use --generate to create one)"
  fi
done < <(find "$SEARCH_PATH" \
  -type d \( -name ".venv" -o -name "venv" -o -name "env" \) \
  ! -path "*/.venv/*/venv" \
  ! -path "$HOME/.cursor/*" \
  ! -path "$HOME/.windsurf/*" \
  ! -path "$HOME/.cache/*" \
  ! -path "$HOME/.local/lib/*" \
  ! -path "$HOME/.rustup/*" \
  2>/dev/null)

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════════════════"
$DRY_RUN && echo "  DRY-RUN SUMMARY" || echo "  CLEANUP SUMMARY"
echo "══════════════════════════════════════════════════════════════════════════"
echo ""
printf "  %-28s %5s dirs\n" "node_modules cleaned"  "$node_count"
printf "  %-28s %5s envs\n" "Python venvs cleaned"  "$venv_count"
$GENERATE && printf "  %-28s %5s files\n" "Manifests generated" "$generated_count"
echo ""

if $DRY_RUN; then
  echo "  Total that WOULD be freed : $(human "$dry_run_total")"
  echo ""
  echo "  Top node_modules by project:"
  for proj in "${!node_proj_sizes[@]}"; do
    echo "    ${node_proj_sizes[$proj]} $proj"
  done | sort -rn | head -10 | while read sz proj; do
    printf "    %10s  %s\n" "$(human "$sz")" "$proj"
  done
  echo ""
  echo "  Top Python venvs:"
  for path in "${!venv_sizes[@]}"; do
    echo "    ${venv_sizes[$path]} $path"
  done | sort -rn | head -10 | while read sz path; do
    printf "    %10s  %s\n" "$(human "$sz")" "$path"
  done
  echo ""
  echo "  ➜  Run without --dry-run to apply."
  $GENERATE && echo "  ➜  --generate will create manifests for all SKIP'd dirs."
else
  echo "  Total freed : $(human "$bytes_freed")"
  echo "  Rebuild node : pnpm install  (per project)"
  echo "  Rebuild py   : uv sync       (per project)"
fi
echo "══════════════════════════════════════════════════════════════════════════"

